version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./workflows:/files/workflows
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
