version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./workflows:/files/workflows
      - ./markdown:/files/markdown
      - ~/.n8n:/home/node/.n8n
