version: "3.8"

services:
  api:
    build: .
    container_name: wai-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
